spring:
  application:
    name: tax-calculator
  datasource:
    url: jdbc:h2:mem:tax_calculator;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
 
  