server:
  port: 8409
spring:
  profiles: default
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddlAuto: create
  datasource:
    platform: h2
    url: jdbc:h2:mem:maintenance_organisation;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE 
    username: maintenance_organisation_db
    password: maintenance_organisation_pw
    driverClassName: org.h2.Driver
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8101/eureka