server:
  port: 8404
spring:
  profiles: default
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddlAuto: create
  datasource:
    platform: h2
    url: jdbc:h2:mem:appliance_status;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE 
    username: appliance_status_db
    password: appliance_status_pw
    driverClassName: org.h2.Driver
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8101/eureka