/* Constituencies */ 

INSERT INTO constituencies(constituency_name) VALUES('Dublin West')
INSERT INTO constituencies(constituency_name) VALUES('Carlow-Kilkenny')
INSERT INTO constituencies(constituency_name) VALUES('Kildare South')
INSERT INTO constituencies(constituency_name) VALUES('Tipperary')
INSERT INTO constituencies(constituency_name) VALUES('Waterford')
INSERT INTO constituencies(constituency_name) VALUES('Limerick City')
INSERT INTO constituencies(constituency_name) VALUES('Dublin Central')
INSERT INTO constituencies(constituency_name) VALUES('Meath East')
INSERT INTO constituencies(constituency_name) VALUES('Kerry')
INSERT INTO constituencies(constituency_name) VALUES('Mayo')
INSERT INTO constituencies(constituency_name) VALUES('Laois')
INSERT INTO constituencies(constituency_name) VALUES('Cork North-Central')
INSERT INTO constituencies(constituency_name) VALUES('Louth')
INSERT INTO constituencies(constituency_name) VALUES('Meath West')
INSERT INTO constituencies(constituency_name) VALUES('Dublin Rathdown')
INSERT INTO constituencies(constituency_name) VALUES('Cork South-West')
INSERT INTO constituencies(constituency_name) VALUES('Dublin Bay South')
INSERT INTO constituencies(constituency_name) VALUES('Dublin Bay North')
INSERT INTO constituencies(constituency_name) VALUES('Dublin South Central')
INSERT INTO constituencies(constituency_name) VALUES('Wicklow')
INSERT INTO constituencies(constituency_name) VALUES('Dublin North-West')
INSERT INTO constituencies(constituency_name) VALUES('Limerick County')
INSERT INTO constituencies(constituency_name) VALUES('Kildare North')
INSERT INTO constituencies(constituency_name) VALUES('Dublin Mid-West')
INSERT INTO constituencies(constituency_name) VALUES('Sligo-Leitrim')
INSERT INTO constituencies(constituency_name) VALUES('Cork East')
INSERT INTO constituencies(constituency_name) VALUES('Donegal')
INSERT INTO constituencies(constituency_name) VALUES('Clare')
INSERT INTO constituencies(constituency_name) VALUES('Galway West')
INSERT INTO constituencies(constituency_name) VALUES('Cork South-Central')
INSERT INTO constituencies(constituency_name) VALUES('Longford-Westmeath')
INSERT INTO constituencies(constituency_name) VALUES('Cork North-West')
INSERT INTO constituencies(constituency_name) VALUES('Dublin Fingal')
INSERT INTO constituencies(constituency_name) VALUES('Offaly')
INSERT INTO constituencies(constituency_name) VALUES('Dún Laoghaire')
INSERT INTO constituencies(constituency_name) VALUES('Wexford')
INSERT INTO constituencies(constituency_name) VALUES('Cavan-Monaghan')
INSERT INTO constituencies(constituency_name) VALUES('Dublin South-West')
INSERT INTO constituencies(constituency_name) VALUES('Galway East')
INSERT INTO constituencies(constituency_name) VALUES('Roscommon-Galway')


/* Political Parties */ 

INSERT INTO political_parties(political_party_name) VALUES('Independent')
INSERT INTO political_parties(political_party_name) VALUES('people Before Profit Alliance')
INSERT INTO political_parties(political_party_name) VALUES('Sinn Féin')
INSERT INTO political_parties(political_party_name) VALUES('Direct Democracy Ireland')
INSERT INTO political_parties(political_party_name) VALUES('Labour Party')
INSERT INTO political_parties(political_party_name) VALUES('Irish Democratic Party')
INSERT INTO political_parties(political_party_name) VALUES('People Before Profit Alliance')
INSERT INTO political_parties(political_party_name) VALUES('Socialist Party')
INSERT INTO political_parties(political_party_name) VALUES('Green Party')
INSERT INTO political_parties(political_party_name) VALUES('Renua')
INSERT INTO political_parties(political_party_name) VALUES('The Workers Party')
INSERT INTO political_parties(political_party_name) VALUES('Fine Gael')
INSERT INTO political_parties(political_party_name) VALUES('Fianna Fáil')
INSERT INTO political_parties(political_party_name) VALUES('Social Democrats')


/* Candidates */ 

INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Catherine Ardagh',1,1)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Heather Humphries',2,2)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Richard Bruton',2,3)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Charlie McConalogue',1,4)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Mary Mitchell-OConnor',2,5)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Eric Byrne',3,1)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Seán Conlan',2,2)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Pat Gallagher',1,4)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Joe OReilly',2,2)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Cahterine Byrne',2,1)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Caoimhghín Ó Caoláin',4,2)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Joan Collins',5,1)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Eamon Ryan',6,6)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Paschal Donohoe',2,7)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Tommy Broughan',5,3)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Joe McHugh',2,4)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Kathryn Reilly',4,2)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Maria Bailey',2,5)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Marie Devine',4,1)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Terence Flanagan',7,3)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Brendan Smith',1,2)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Pearse Doherty',4,4)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Sean Haughey',1,3)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Cormac Devlin',1,5)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Mary Fitzpatrick',1,7)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Niamh Smyth',1,2)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Alex White',3,6)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Paul Hand',5,1)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Padraig MacLochlainn',4,4)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Aengus Ó Snodaigh',4,1)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Mary Smyth',7,2)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Joe Costello',3,7)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Mary Hanafin',1,5)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Jimmy Deenihan',2,8)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Colm Brophy',2,9)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Brid Smith',8,1)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Deirdre Heney',1,3)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Carrie Smyth',3,5)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Oisín Ó hAlmhain',6,1)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Brendan Griffin',2,8)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Thomas Pringle',5,4)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Fergus ODowd',2,10)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Anne-Marie Dermody',2,9)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Richard Murray',5,1)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Shane OBrien',4,5)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Mary Lou McDonald',4,7)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Peter Casey',5,4)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Peter Fitzpatrick',2,10)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Grace ODonnell',2,8)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Cian OCallaghan',9,3)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Declan Breathnach',1,10)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Niamh Kennedy',5,4)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Alan Shatter',2,11)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Gerry Adams',4,10)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Norma Moriarty',1,8)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Richard Boyd-Barrett',8,5)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Karen Warren',2,9)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('John ODonnell',5,4)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Gary Gannon',9,7)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Josepha Madigan',2,11)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('John Brassil',1,8)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Imelda Munster',4,10)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Aodhan O Riordan',3,3)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michael Healy Rae',5,8)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Frank Cronin',7,5)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Martin Ferris',4,8)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Arthur Spring',3,8)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('John Lahart',1,9)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Ãilis Ryan',10,7)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Ossian Smyth',6,5)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Enda Kenny',2,12)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('John Lyons',8,3)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Brian Finucane',8,8)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Mary White',1,11)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Carol Hunt',5,5)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Pamela Kearns',3,9)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Alex White',3,11)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michael Ring',2,12)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Stephanie Regan',2,3)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Diana ODwyer',5,7)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Tom Fleming',5,8)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michelle Mulherin',2,12)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Averil Power',5,3)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Mick Duff',3,9)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michael OGorman',5,8)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Lisa Chambers',1,12)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Sorcha Nic Cormaic',4,11)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Naoise O Muiri',2,3)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Dara Calleary',1,12)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Sarah Holland',4,9)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Catherine Martin',6,11)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michael Noonan',2,13)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michael Mac Donncha',4,3)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Rose Conway-Walsh',4,12)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Sean Crowe',4,9)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Denise Mitchell',4,3)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Christy Burke',5,7)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Tom Moran',8,12)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Paul Connaughton',2,14)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Ciaran Cannon',2,14)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michael Farrington',7,12)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Willie ODea',1,13)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Finian McGrath',5,3)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Cieran Perry',5,7)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Shane Ross',5,11)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Anne Rabbitte',1,14)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Maurice Quinlivan',4,13)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Jerry Buttimer',2,15)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Gerry OBoyle',5,12)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Jan OSullivan',3,13)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('David Healy',6,3)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Maureen OSullivan',5,7)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Paul Murphy',5,9)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Marcella Corcoran-Kennedy',2,16)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Simon Coveney',2,15)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Colm Keaveney',1,14)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Peter Matthews',5,11)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Kieran ODonnell',2,13)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Jimmy Guerin',5,3)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Nicola Curry',5,11)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Lorraine Higgins',3,14)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Micheal Martin',1,15)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Cian Prendiville',5,13)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Sandra Fay',5,9)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Damien English',2,17)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Annemarie Roche',4,14)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michael McGrath',1,15)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Sarah Jane Hennelly',9,13)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Andrew Kelly',5,7)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Desmond J Hayes',7,13)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Donna Cooney',6,3)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Sean Canney',5,14)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Barry Cowen',1,16)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michael Fahy',5,14)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Paul Clarke',5,3)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('John Deasy',2,18)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Ciaran Lynch',3,15)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Shane Cassells',1,17)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Eddie Fitzpatrick',1,16)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Paudie Coffey',2,11)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Ronan McMahon',7,9)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Carol Nolan',4,16)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Noel Rock',2,19)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('John Leahy',7,16)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Katherine Zappone',5,9)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Mary Butler',1,18)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Paul McAuliffe',1,19)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Thomas Gould',4,20)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Ken Smollen',11,16)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Hildegarde Naughten',2,21)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Deirdre ODonovan',5,9)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Ciara Conway',3,18)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Tracy McElhinney',3,17)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('John Foley',5,16)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Mick Barry',5,20)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Sean Kyne',2,21)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Peadar TÃ³ibín',4,17)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('David Cullinane',4,18)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Kathleen Lynch',3,20)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Brian Walsh',2,21)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Eamonn Maloney',5,9)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Seamus McMenamin',6,17)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Johnathan OBrien',4,20)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('John OMahony',2,21)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Eamon OCuiv',1,21)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Mailo Power',7,18)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Peter Fitzpatrick',5,9)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Mary Moran',3,10)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('John Lyons',3,19)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Billy Kelleher',1,20)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Gerald Nash',3,10)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Mary Hoade',1,21)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Una Dunphy',8,18)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('John Connolly',1,21)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Dara Murphy',2,20)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Derek Nolan',3,21)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Trevor OClochartaigh',4,21)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Tommy Holohan',5,21)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michael ODowd',7,10)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('John Halligan',5,18)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Declan Burke',5,9)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Niall Ó Tuathail',9,21)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Oliver Moran',6,20)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Seamus Sheridan',6,21)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Tommy Roddy',5,21)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Seona OFegan',5,21)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Ted Tynan',10,20)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('James Charity',5,21)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Fidelma Healy Eames',5,21)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Noel Grealish',5,21)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Catherine Connolly',5,21)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Cormac Mckay',5,7)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Eoghan Murphy',2,6)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Kate OConnell',2,6)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Jim OCallaghan',1,6)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Kevin Humphreys',3,6)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Chris Andrews',4,6)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Annette Mooney',8,6)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Gareth Weldon',8,10)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Mark Dearey',6,10)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Anthony Connor',12,10)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Pat Deering',2,22)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Pat Greene',12,10)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('John Paul Phelan',2,22)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Jeff Rudd',5,10)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('David Fitzgerald',2,22)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Kevin Callan',5,10)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('John McGuinness',1,22)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Maeve Yore',5,10)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Bobby Aylward',1,22)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Jennifer Murnane OConnor',1,22)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Ann Phelan',3,22)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Kathleen Funchion',4,22)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Malcolm Noonan',6,22)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Patrick McKee',7,22)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Noel Walsh',5,22)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Andrew Doyle',2,23)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Simon Harris',2,23)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Jennifer Cuffe',1,23)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Pat Casey',1,23)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Anne Ferris',3,23)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('John Brady',4,23)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Anna Doyle',5,23)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Sharon Briggs',8,23)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Billly Timmins',7,23)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Maura Hopkins',2,24)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Anne Farrell',7,24)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Eddie Conroy',13,24)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Paul Kehoe',2,25)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Brendan Howlin',3,25)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michael DArcy',2,25)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Malcolm Byrne',1,25)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('James Browne',1,25)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Mick Wallace',5,25)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Stephen Donnelly',9,23)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Steven Matthews',6,23)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Joe Behan',5,23)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Pat Kavanagh',5,23)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Charlie Keddy',5,23)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Sean Canney',5,24)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Colm Keaveney',1,14)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Paul Connaughton',2,14)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Ciaran Cannon',2,14)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Lorraine Higgins',3,14)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Anne Marie Roche',4,14)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Anne Rabbitte',1,14)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michael Fahy',5,14)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('John Kelly',3,24)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Claire Kerrane',4,24)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Robert Troy',1,26)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Paul Hogan',4,26)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Gabrielle McFadden',2,26)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('James Bannon',2,26)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Kevin Boxer Moran',5,26)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Peter Burke',2,26)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Gerry Warnock',9,26)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Barbara Smyth',5,26)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Rachel Grimes',7,26)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Jimmy Duffy',8,26)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Pat Breen',2,27)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Joe Carey',2,27)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Johnny Mythen',4,25)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Deirdre Wadding',8,25)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Leonard Kelly',9,25)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('David Lloyd',12,25)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Caroline Foxe',5,25)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Emmet Moloney',5,25)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Breda Cahill',5,25)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Anthony Lawlor',2,28)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Bernard Durkan',2,28)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('James Lawless',1,28)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Frank ORourke',1,28)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Emmett Stagg',3,28)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('RÃ©ada Cronin',4,28)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Catherine Murphy',9,28)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Ashling Merriman',8,28)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Brendan Young',5,28)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('James Reilly',2,29)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Alan Farrell',2,29)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Darragh OBrien',1,29)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Lorraine Clifford Lee',1,29)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Brendan Ryan',3,29)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Louise OReilly',4,29)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Joe OBrien',6,29)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Barry Martin',8,29)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Terry Kelleher',5,29)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Clare Daly',5,29)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Roslyn Fuller',5,29)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Tony Murphy',5,29)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Noel Coonan',2,30)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Tom Hayes',2,30)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Marie Murphy',2,30)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Jackie Cahill',1,30)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Siobhan Ambrose',1,30)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michael Smith',1,30)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Alan Kelly',3,30)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Seamus Morris',4,30)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Seamus Healy',5,30)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michael Lowry',5,30)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Gerry Reynolds',2,31)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Tony McLoughlin',2,31)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Eamon Scanlon',1,31)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Marc MacSharry',1,31)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Susan OKeefe',3,31)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Martin Kenny',4,31)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Chris MacManus',4,31)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Finbarr Filan',7,31)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Nigel Gallagher',8,31)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Leslie OHora',6,31)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Marie Casserly',5,31)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Declan Bree',5,31)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Bernard Sweeney',5,31)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Patrick ODonovan',2,32)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Tom Neville',2,32)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Niall Collins',1,32)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Seamus Browne',4,32)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('James Heffernan',9,32)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Emmett OBrien',5,32)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Patricia Ryan',4,33)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Sean O OFearghail',1,33)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Fiona McLoughlin',1,33)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Regina Doherty',2,34)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Fiona McLoughlin-Healy',2,33)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Martin Heydon',2,33)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Helen McEntee',2,34)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Mark Wall',3,33)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Thomas Byrne',1,34)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Dominic Hannigan',3,34)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Darren ORourke',4,34)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Seán Ó Buachalla',6,34)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('SÃ©amus McDonagh',10,34)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Aisling ONeill',9,34)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Ben Gilroy',12,34)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Sharon Keogan',5,34)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Lorraine Hayde',5,33)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Charlie Flanagan',2,35)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Thomasina Connell',2,35)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Catherine Noone',2,36)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('John Whelan',3,35)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Leo Varadkar',2,36)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Jack Chambers',1,36)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Sean Fleming',1,35)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Joan Burton',3,36)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Paul Donnelly',4,36)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Ruth Coppinger',14,36)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Brian Stanley',4,35)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Sinead Moore',6,35)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Roderic OGorman',6,36)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Lorna Nolan',5,36)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('David McGuinness',5,36)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('TJ Clare',5,36)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Aine Collins',2,37)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michael Creed',2,37)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michael Moynihan',1,37)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Aindrias Moynihan',1,37)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Nigel Dennehy',4,37)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Cork Manning',6,37)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('John Paul OShea',5,37)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Steven ORiordabn',5,37)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Diarmuid OFlynn',5,37)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Frances Fitzgerald',2,38)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Derek Keating',2,38)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('John Curran',1,38)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Joanna Tuffy',3,38)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Eoin Ó Broin',4,38)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Gino Kenny',8,38)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Anne-Marie McNally',9,38)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Francis Timmons',5,38)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Donnchadh Ó Laoghaire',4,20)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Lorna Bogue',6,15)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Jim OConnell',8,15)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Rose Leadbetter',5,15)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Mick Finn',5,15)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Diarmaid Ó Cadhla',5,15)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Richard Cahill',5,27)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Adrienne Wallace',8,22)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Conor Mac Liam',5,22)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Timmy Dooley',1,27)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michael McDonagh',1,27)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Clare Colleran Molloy',1,27)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Ann Norton',5,27)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michael McNamara',3,27)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Noeleen Moran',4,27)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Kevin OKeefe',1,39)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Tom Barry',1,39)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('David Stanton',2,39)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Sean Sherlock',3,39)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Pat Buckley',4,39)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Ciara Leonardi Roche',5,39)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Paul Bradford',7,39)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Ken Curtain',9,39)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Ken Curtain',9,39)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Claire Cullinane',5,39)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Noel Harrington',2,40)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Jim Daly',2,40)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Margaret Murphy OMahony',1,40)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michael McCarthy',3,40)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Rachel McCarthy',4,40)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Alan Coleman',5,40)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Michael Collins',5,40)
INSERT INTO candidates(candidate_name,political_party_id,constituency_id) VALUES('Andrew Keegan',8,19)


/* Constituency Votes */ 

INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(36,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(22,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(33,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(30,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(18,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(13,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(7,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(34,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(8,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(12,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(35,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(20,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(10,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(17,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(11,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(40,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(6,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(3,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(1,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(23,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(19,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(32,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(28,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(38,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(31,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(39,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(4,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(27,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(21,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(15,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(26,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(37,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(29,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(16,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(5,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(25,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(2,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(9,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(14,0,0)
INSERT INTO constituency_votes(constituency_id, valid_votes, invalid_votes) VALUES(24,0,0)
