server:
  port: 8103
turbine:
  stream:
    port: 8300
management:
  port: 8301
spring:
  profiles: default
  rabbitmq:
    host: localhost
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8101/eureka