application: diy-tourism
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /rest/.*
  script: main.py
  
- url: /public
  static_dir: public
  
- url: (.*)/
  static_files: public/index.html
  upload: /public/index.html