server:
  port: 8414
spring:
  profiles: default
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddlAuto: create
  datasource:
    platform: h2
    url: jdbc:h2:mem:diagnostic_request;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE 
    username: diagnostic_request_db
    password: diagnostic_request_pw
    driverClassName: org.h2.Driver
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8101/eureka